In [14]:
# Import library yang dibutuhkan
import pandas as pd

In [26]:
# Memanggil data dari file CSV
df = pd.read_excel("/content/CAD alizadeh (1).xls")

In [27]:
# Menampilkan 5 data teratas
df.head()

,No,Age,Weight,Length,Sex,BMI,DM,HTN,Current Smoker,EX-Smoker,...,K,Na,WBC,Lymph,Neut,PLT,EF-TTE,Region RWMA,VHD,Cath
0,1,53,90,175,Male,29.387755,0,1,1,0,...,4.7,141,5700,39,52,261,50,0,N,Cad
1,2,67,70,157,Fmale,28.398718,0,1,0,0,...,4.7,156,7700,38,55,165,40,4,N,Cad
2,3,54,54,164,Male,20.077335,0,0,1,0,...,4.7,139,7400,38,60,230,40,2,mild,Cad
3,4,66,67,158,Fmale,26.838648,0,1,0,0,...,4.4,142,13000,18,72,742,55,0,Severe,Normal
4,5,50,87,153,Fmale,37.165193,0,1,0,0,...,4.0,140,9200,55,39,274,50,0,Severe,Normal

In [28]:
# Melihat informasi dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 56 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   No                     303 non-null    int64
 1   Age                    303 non-null    int64
 2   Weight                 303 non-null    int64
 3   Length                 303 non-null    int64
 4   Sex                    303 non-null    object
 5   BMI                    303 non-null    float64
 6   DM                     303 non-null    int64
 7   HTN                    303 non-null    int64
 8   Current Smoker         303 non-null    int64
 9   EX-Smoker              303 non-null    int64
 10  FH                     303 non-null    int64
 11  Obesity                303 non-null    object
 12  CRF                    303 non-null    object
 13  CVA                    303 non-null    object
 14  Airway disease         303 non-null    object
 15  Thyroid Disease        303 non-null    object
 16  CHF                    303 non-null    object
 17  DLP                    303 non-null    object
 18  BP                     303 non-null    int64
 19  PR                     303 non-null    int64
 20  Edema                  303 non-null    int64
 21  Weak Peripheral Pulse  303 non-null    object
 22  Lung rales             303 non-null    object
 23  Systolic Murmur        303 non-null    object
 24  Diastolic Murmur       303 non-null    object
 25  Typical Chest Pain     303 non-null    int64
 26  Dyspnea                303 non-null    object
 27  Function Class         303 non-null    int64
 28  Atypical               303 non-null    object
 29  Nonanginal             303 non-null    object
 30  Exertional CP          303 non-null    object
 31  LowTH Ang              303 non-null    object
 32  Q Wave                 303 non-null    int64
 33  St Elevation           303 non-null    int64
 34  St Depression          303 non-null    int64
 35  Tinversion             303 non-null    int64
 36  LVH                    303 non-null    object
 37  Poor R Progression     303 non-null    object
 38  FBS                    303 non-null    int64
 39  CR                     303 non-null    float64
 40  TG                     303 non-null    int64
 41  LDL                    303 non-null    int64
 42  HDL                    303 non-null    float64
 43  BUN                    303 non-null    int64
 44  ESR                    303 non-null    int64
 45  HB                     303 non-null    float64
 46  K                      303 non-null    float64
 47  Na                     303 non-null    int64
 48  WBC                    303 non-null    int64
 49  Lymph                  303 non-null    int64
 50  Neut                   303 non-null    int64
 51  PLT                    303 non-null    int64
 52  EF-TTE                 303 non-null    int64
 53  Region RWMA            303 non-null    int64
 54  VHD                    303 non-null    object
 55  Cath                   303 non-null    object
dtypes: float64(5), int64(30), object(21)
memory usage: 132.7+ KB

In [31]:
# Melihat statistik
df.describe()

,No,Age,Weight,Length,BMI,DM,HTN,Current Smoker,EX-Smoker,FH,...,ESR,HB,K,Na,WBC,Lymph,Neut,PLT,EF-TTE,Region RWMA
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,...,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,152.000000,58.897690,73.831683,164.716172,27.248339,0.297030,0.590759,0.207921,0.033003,0.158416,...,19.462046,13.153465,4.230693,140.996700,7562.046205,32.399340,60.148515,221.488449,47.231023,0.620462
std,87.612784,10.392278,11.987358,9.327661,4.098865,0.457706,0.492507,0.406491,0.178941,0.365734,...,15.936475,1.610452,0.458202,3.807885,2413.739323,9.972592,10.182493,60.796199,8.927194,1.132531
min,1.000000,30.000000,48.000000,140.000000,18.115413,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,8.900000,3.000000,128.000000,3700.000000,7.000000,32.000000,25.000000,15.000000,0.000000
25%,76.500000,51.000000,65.000000,158.000000,24.514380,0.000000,0.000000,0.000000,0.000000,0.000000,...,9.000000,12.200000,3.900000,139.000000,5800.000000,26.000000,52.500000,183.500000,45.000000,0.000000
50%,152.000000,58.000000,74.000000,165.000000,26.775510,0.000000,1.000000,0.000000,0.000000,0.000000,...,15.000000,13.200000,4.200000,141.000000,7100.000000,32.000000,60.000000,210.000000,50.000000,0.000000
75%,227.500000,66.000000,81.000000,171.000000,29.411765,1.000000,1.000000,0.000000,0.000000,0.000000,...,26.000000,14.200000,4.500000,143.000000,8800.000000,39.000000,67.000000,250.000000,55.000000,1.000000
max,303.000000,86.000000,120.000000,188.000000,40.900658,1.000000,1.000000,1.000000,1.000000,1.000000,...,90.000000,17.600000,6.600000,156.000000,18000.000000,60.000000,89.000000,742.000000,60.000000,4.000000

In [30]:
# Menampilkan 5 data terbawah
df.tail()

,No,Age,Weight,Length,Sex,BMI,DM,HTN,Current Smoker,EX-Smoker,...,K,Na,WBC,Lymph,Neut,PLT,EF-TTE,Region RWMA,VHD,Cath
298,299,58,84,168,Male,29.761905,0,0,0,0,...,4.8,146,8500,34,58,251,45,0,N,Cad
299,300,55,64,152,Fmale,27.700831,0,0,0,0,...,4.0,139,11400,16,80,377,40,0,mild,Normal
300,301,48,77,160,Fmale,30.078125,0,1,0,0,...,4.0,140,9000,35,55,279,55,0,N,Normal
301,302,57,90,159,Fmale,35.599858,1,0,0,0,...,3.8,141,3800,48,40,208,55,0,N,Normal
302,303,56,85,170,Fmale,29.411765,0,1,1,0,...,4.4,147,6000,32,55,302,55,0,N,Cad

In [32]:
# Mengecek jumlah data kosong tiap kolom
df.isnull().sum()

No                       0
Age                      0
Weight                   0
Length                   0
Sex                      0
BMI                      0
DM                       0
HTN                      0
Current Smoker           0
EX-Smoker                0
FH                       0
Obesity                  0
CRF                      0
CVA                      0
Airway disease           0
Thyroid Disease          0
CHF                      0
DLP                      0
BP                       0
PR                       0
Edema                    0
Weak Peripheral Pulse    0
Lung rales               0
Systolic Murmur          0
Diastolic Murmur         0
Typical Chest Pain       0
Dyspnea                  0
Function Class           0
Atypical                 0
Nonanginal               0
Exertional CP            0
LowTH Ang                0
Q Wave                   0
St Elevation             0
St Depression            0
Tinversion               0
LVH                      0
Poor R Progression       0
FBS                      0
CR                       0
TG                       0
LDL                      0
HDL                      0
BUN                      0
ESR                      0
HB                       0
K                        0
Na                       0
WBC                      0
Lymph                    0
Neut                     0
PLT                      0
EF-TTE                   0
Region RWMA              0
VHD                      0
Cath                     0
dtype: int64

In [33]:
# Jika ingin mengisi nilai kosong dengan rata-rata (untuk kolom numerik)
df = df.fillna(df.mean(numeric_only=True))

In [34]:
# Jika ingin menghapus baris yang memiliki data kosong:
df = df.dropna()

In [35]:
# Mengubah kolom bertipe object/kategori menjadi numerik:
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].astype('category').cat.codes

print("Semua kolom sudah menjadi numerik")

Semua kolom sudah menjadi numerik

In [24]:
# Cek kembali tipe data:
df.dtypes

No                         int64
Age                        int64
Weight                     int64
Length                     int64
Sex                         int8
BMI                      float64
DM                         int64
HTN                        int64
Current Smoker             int64
EX-Smoker                  int64
FH                         int64
Obesity                     int8
CRF                         int8
CVA                         int8
Airway disease              int8
Thyroid Disease             int8
CHF                         int8
DLP                         int8
BP                         int64
PR                         int64
Edema                      int64
Weak Peripheral Pulse       int8
Lung rales                  int8
Systolic Murmur             int8
Diastolic Murmur            int8
Typical Chest Pain         int64
Dyspnea                     int8
Function Class             int64
Atypical                    int8
Nonanginal                  int8
Exertional CP               int8
LowTH Ang                   int8
Q Wave                     int64
St Elevation               int64
St Depression              int64
Tinversion                 int64
LVH                         int8
Poor R Progression          int8
FBS                        int64
CR                       float64
TG                         int64
LDL                        int64
HDL                      float64
BUN                        int64
ESR                        int64
HB                       float64
K                        float64
Na                         int64
WBC                        int64
Lymph                      int64
Neut                       int64
PLT                        int64
EF-TTE                     int64
Region RWMA                int64
VHD                         int8
Cath                        int8
dtype: object

In [36]:
# Normalisasi setiap tabel
df_normalized = (df - df.min()) / (df.max() - df.min())

# Menampilkan hasil normalisasi
df_normalized.head()

,No,Age,Weight,Length,Sex,BMI,DM,HTN,Current Smoker,EX-Smoker,...,K,Na,WBC,Lymph,Neut,PLT,EF-TTE,Region RWMA,VHD,Cath
0,0.000000,0.410714,0.583333,0.729167,1.0,0.494721,0.0,1.0,1.0,0.0,...,0.472222,0.464286,0.139860,0.603774,0.350877,0.329149,0.777778,0.0,0.333333,0.0
1,0.003311,0.660714,0.305556,0.354167,0.0,0.451314,0.0,1.0,0.0,0.0,...,0.472222,1.000000,0.279720,0.584906,0.403509,0.195258,0.555556,1.0,0.333333,0.0
2,0.006623,0.428571,0.083333,0.500000,1.0,0.086105,0.0,0.0,1.0,0.0,...,0.472222,0.392857,0.258741,0.584906,0.491228,0.285914,0.555556,0.5,1.000000,0.0
3,0.009934,0.642857,0.263889,0.375000,0.0,0.382846,0.0,1.0,0.0,0.0,...,0.388889,0.500000,0.650350,0.207547,0.701754,1.000000,0.888889,0.0,0.666667,1.0
4,0.013245,0.357143,0.541667,0.270833,0.0,0.836058,0.0,1.0,0.0,0.0,...,0.277778,0.428571,0.384615,0.905660,0.122807,0.347280,0.777778,0.0,0.666667,1.0